'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { Calculator, ShieldCheck, Download, ArrowRight, CheckCircle2, Sparkles, AlertCircle } from 'lucide-react';
import { useConfig } from '@/context/ConfigContext';

export default function HraCalculatorPage() {
  const { taxRates } = useConfig();
  const metroPercentNum = taxRates.hraMetroPercent || 50;
  const nonMetroPercentNum = taxRates.hraNonMetroPercent || 40;
  const metroRate = metroPercentNum / 100;
  const nonMetroRate = nonMetroPercentNum / 100;

  const [period, setPeriod] = useState<'monthly' | 'yearly'>('monthly');
  const [basicSalary, setBasicSalary] = useState(50000);
  const [da, setDa] = useState(0);
  const [hraReceived, setHraReceived] = useState(25000);
  const [rentPaid, setRentPaid] = useState(20000);
  const [isMetro, setIsMetro] = useState(true); // Metro vs non-metro percentage
  const [taxBracket, setTaxBracket] = useState(0.20); // 20% or 30%

  // Multiplier if monthly
  const mult = period === 'monthly' ? 12 : 1;
  const annualSalary = (Number(basicSalary) + Number(da)) * mult;
  const annualHra = Number(hraReceived) * mult;
  const annualRent = Number(rentPaid) * mult;

  // Rule 1: Actual HRA received
  const rule1 = annualHra;
  // Rule 2: 50% or 40% (dynamic) of salary
  const rule2 = annualSalary * (isMetro ? metroRate : nonMetroRate);
  // Rule 3: Rent paid - 10% of salary
  const rule3 = Math.max(0, annualRent - (0.10 * annualSalary));

  // Exemption is minimum of the three
  const exemptHraAnnual = Math.min(rule1, rule2, rule3);
  const taxableHraAnnual = Math.max(0, annualHra - exemptHraAnnual);
  const taxSaved = exemptHraAnnual * taxBracket;

  const downloadHraStatement = () => {
    const lines = [
      '========================================================================',
      '                 TRAC CONSULTANT - HRA EXEMPTION COMPUTATION             ',
      `                 Section 10(13A) of Income Tax Act • Rule 2A             `,
      `                 Financial Year: ${taxRates.financialYear || 'FY 2024-25'} | AY: ${taxRates.assessmentYear || 'AY 2025-26'}               `,
      '========================================================================',
      '',
      'INPUT PARAMETERS:',
      `- Frequency Mode             : ${period === 'monthly' ? 'Monthly' : 'Annual (Yearly)'}`,
      `- Basic Salary (${period})   : Rs. ${Number(basicSalary).toLocaleString('en-IN')}`,
      `- Dearness Allowance (DA)    : Rs. ${Number(da).toLocaleString('en-IN')}`,
      `- Total Annual Salary (Basic+DA) : Rs. ${annualSalary.toLocaleString('en-IN')}`,
      `- HRA Received (${period})   : Rs. ${Number(hraReceived).toLocaleString('en-IN')} (Annual: Rs. ${annualHra.toLocaleString('en-IN')})`,
      `- Rent Paid (${period})      : Rs. ${Number(rentPaid).toLocaleString('en-IN')} (Annual: Rs. ${annualRent.toLocaleString('en-IN')})`,
      `- Accommodation City         : ${isMetro ? `Metro City (${metroPercentNum}% Rule - Delhi, Mumbai, Kolkata, Chennai)` : `Non-Metro City (${nonMetroPercentNum}% Rule)`}`,
      `- Selected Tax Slab Rate     : ${(taxBracket * 100).toFixed(0)}% Bracket`,
      '',
      'STATUTORY 3-CONDITION COMPUTATION (Least is Exempt):',
      `1. Actual HRA Received               : Rs. ${Math.round(rule1).toLocaleString('en-IN')}`,
      `2. ${isMetro ? metroPercentNum : nonMetroPercentNum}% of Salary (Basic + DA)       : Rs. ${Math.round(rule2).toLocaleString('en-IN')}`,
      `3. Rent Paid in excess of 10% Salary : Rs. ${Math.round(rule3).toLocaleString('en-IN')}`,
      '------------------------------------------------------------------------',
      `TOTAL EXEMPT HRA UNDER SEC 10(13A)   : Rs. ${Math.round(exemptHraAnnual).toLocaleString('en-IN')} (ANNUAL)`,
      `TAXABLE HRA (Included in Income)     : Rs. ${Math.round(taxableHraAnnual).toLocaleString('en-IN')}`,
      `ESTIMATED ANNUAL TAX SAVINGS         : Rs. ${Math.round(taxSaved).toLocaleString('en-IN')}`,
      '------------------------------------------------------------------------',
      '',
      'LEGAL COMPLIANCE INSTRUCTIONS:',
      '- If annual rent exceeds Rs. 1,00,000, landlord PAN is mandatory to report to employer in Form 12BB.',
      '- Keep rent receipts, rent agreement, and bank transfer proofs ready for potential IT verification.',
      '- HRA exemption can only be claimed if you reside in a rented house and actually pay rent.',
      '',
      'Generated by Trac Consultant Tax Suite (https://tracconsultant.com)',
      '========================================================================'
    ];

    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `HRA_Exemption_Statement_${(taxRates.financialYear || 'FY2024-25').replace(/\s+/g, '')}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-slate-50/70 pb-20">
      {/* Top Banner - FinTech Gradient */}
      <div className="bg-gradient-to-b from-[#07152B] via-[#0B1E3B] to-[#0D2447] text-white pt-10 pb-10 sm:pt-12 sm:pb-12 px-4 sm:px-8 border-b border-[#143258] relative overflow-hidden">
        <div className="absolute top-0 right-0 w-96 h-96 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="max-w-5xl mx-auto flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 relative z-10">
          <div>
            <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-400 text-xs font-bold uppercase tracking-wider mb-2 border border-emerald-500/30">
              <Calculator className="w-3.5 h-3.5" /> Section 10(13A) • Rule 2A
            </div>
            <h1 className="text-2xl sm:text-4xl font-black tracking-tight text-white">HRA Exemption Calculator</h1>
            <p className="text-xs sm:text-sm text-slate-300 mt-1">
              Accurate legal calculation of House Rent Allowance exemption with maximum tax savings.
            </p>
          </div>
          <Link
            href="/tools"
            className="text-xs font-bold text-slate-200 hover:text-white bg-white/10 hover:bg-white/15 px-4 py-2.5 rounded-xl border border-white/10 transition-colors backdrop-blur-sm"
          >
            ← Back to All Tools
          </Link>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-4 sm:px-8 pt-8 relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          {/* Left Column: Calculator Inputs */}
          <div className="lg:col-span-7 bg-white rounded-3xl p-6 sm:p-8 shadow-sm border border-slate-200 space-y-5">
            <div className="flex items-center justify-between pb-4 border-b border-slate-100">
              <h2 className="text-base font-bold text-slate-900">Salary & Rent Parameters</h2>
              <div className="flex p-1 bg-slate-100 rounded-xl text-xs font-bold text-slate-600">
                <button
                  type="button"
                  onClick={() => setPeriod('monthly')}
                  className={`px-3 py-1 rounded-lg transition-all ${period === 'monthly' ? 'bg-white text-slate-900 shadow-sm' : ''}`}
                >
                  Monthly
                </button>
                <button
                  type="button"
                  onClick={() => setPeriod('yearly')}
                  className={`px-3 py-1 rounded-lg transition-all ${period === 'yearly' ? 'bg-white text-slate-900 shadow-sm' : ''}`}
                >
                  Annual (Yearly)
                </button>
              </div>
            </div>

            {/* Basic Salary */}
            <div>
              <div className="flex justify-between items-center mb-1 text-xs font-semibold text-slate-700">
                <label>Basic Salary ({period}):</label>
                <span className="font-mono font-bold text-emerald-700">₹{Number(basicSalary).toLocaleString('en-IN')}</span>
              </div>
              <input
                type="number"
                value={basicSalary}
                onChange={(e) => setBasicSalary(Number(e.target.value))}
                className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-semibold text-slate-900 focus:outline-none focus:ring-2 focus:ring-emerald-500"
              />
            </div>

            {/* DA */}
            <div>
              <div className="flex justify-between items-center mb-1 text-xs font-semibold text-slate-700">
                <label>Dearness Allowance (DA forming part of salary):</label>
                <span className="font-mono font-bold text-slate-600">₹{Number(da).toLocaleString('en-IN')}</span>
              </div>
              <input
                type="number"
                value={da}
                onChange={(e) => setDa(Number(e.target.value))}
                className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-semibold text-slate-900 focus:outline-none focus:ring-2 focus:ring-emerald-500"
              />
            </div>

            {/* HRA Received */}
            <div>
              <div className="flex justify-between items-center mb-1 text-xs font-semibold text-slate-700">
                <label>HRA Received from Employer ({period}):</label>
                <span className="font-mono font-bold text-emerald-700">₹{Number(hraReceived).toLocaleString('en-IN')}</span>
              </div>
              <input
                type="number"
                value={hraReceived}
                onChange={(e) => setHraReceived(Number(e.target.value))}
                className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-semibold text-slate-900 focus:outline-none focus:ring-2 focus:ring-emerald-500"
              />
            </div>

            {/* Total Rent Paid */}
            <div>
              <div className="flex justify-between items-center mb-1 text-xs font-semibold text-slate-700">
                <label>Total Actual Rent Paid ({period}):</label>
                <span className="font-mono font-bold text-indigo-700">₹{Number(rentPaid).toLocaleString('en-IN')}</span>
              </div>
              <input
                type="number"
                value={rentPaid}
                onChange={(e) => setRentPaid(Number(e.target.value))}
                className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-semibold text-slate-900 focus:outline-none focus:ring-2 focus:ring-emerald-500"
              />
            </div>

            {/* City Type */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-2">City of Rented Accommodation:</label>
              <div className="grid grid-cols-2 gap-3">
                <button
                  type="button"
                  onClick={() => setIsMetro(true)}
                  className={`p-3 rounded-2xl border text-left transition-all ${
                    isMetro
                      ? 'border-emerald-600 bg-emerald-50/50 shadow-sm text-emerald-900 font-bold'
                      : 'border-slate-200 text-slate-600 hover:bg-slate-50'
                  }`}
                >
                  <div className="text-xs">Metro City ({metroPercentNum}%)</div>
                  <div className="text-[10px] text-slate-400 font-normal">Delhi, Mumbai, Kolkata, Chennai</div>
                </button>
                <button
                  type="button"
                  onClick={() => setIsMetro(false)}
                  className={`p-3 rounded-2xl border text-left transition-all ${
                    !isMetro
                      ? 'border-emerald-600 bg-emerald-50/50 shadow-sm text-emerald-900 font-bold'
                      : 'border-slate-200 text-slate-600 hover:bg-slate-50'
                  }`}
                >
                  <div className="text-xs">Non-Metro ({nonMetroPercentNum}%)</div>
                  <div className="text-[10px] text-slate-400 font-normal">Bengaluru, Pune, Hyderabad, Kanpur, etc.</div>
                </button>
              </div>
            </div>

            {/* Tax Bracket */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-2">Your Applicable Tax Bracket:</label>
              <div className="grid grid-cols-3 gap-2">
                {[
                  { label: '5% Bracket', val: 0.05 },
                  { label: '20% Bracket', val: 0.20 },
                  { label: '30% Bracket', val: 0.30 }
                ].map(b => (
                  <button
                    key={b.val}
                    type="button"
                    onClick={() => setTaxBracket(b.val)}
                    className={`p-2 rounded-xl border text-center text-xs font-bold transition-all ${
                      taxBracket === b.val
                        ? 'border-emerald-600 bg-emerald-600 text-white shadow-sm'
                        : 'border-slate-200 text-slate-600 hover:bg-slate-50'
                    }`}
                  >
                    {b.label}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Right Column: Statutory Rules & Results */}
          <div className="lg:col-span-5 space-y-6">
            <div className="bg-gradient-to-br from-emerald-900 via-slate-900 to-slate-950 text-white rounded-3xl p-6 sm:p-8 shadow-xl relative overflow-hidden">
              <div className="absolute top-0 right-0 w-48 h-48 bg-emerald-500/10 rounded-full blur-2xl pointer-events-none" />

              <span className="text-[11px] font-bold text-emerald-400 uppercase tracking-wider">
                Exemption Result (Annual)
              </span>

              <div className="mt-3 pb-4 border-b border-slate-800">
                <div className="text-xs text-slate-400">Total HRA Exempt u/s 10(13A):</div>
                <div className="text-3xl sm:text-4xl font-black text-emerald-400 mt-1">
                  ₹{Math.round(exemptHraAnnual).toLocaleString('en-IN')}
                </div>
                <div className="text-xs text-slate-300 mt-2 flex items-center gap-1.5">
                  <Sparkles className="w-4 h-4 text-emerald-400" />
                  <span>Estimated Tax Saved: <strong className="text-white">₹{Math.round(taxSaved).toLocaleString('en-IN')}</strong></span>
                </div>
              </div>

              {/* Taxable HRA */}
              <div className="py-4 border-b border-slate-800 flex justify-between items-center text-xs">
                <span className="text-slate-400">Taxable HRA (Added to Salary):</span>
                <span className="font-bold text-white font-mono">₹{Math.round(taxableHraAnnual).toLocaleString('en-IN')}</span>
              </div>

              {/* 3 Statutory Rules Breakdown */}
              <div className="pt-4 space-y-2.5">
                <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">Least of the 3 is exempt:</p>
                <div className={`p-2.5 rounded-xl border text-xs flex justify-between items-center ${
                  exemptHraAnnual === rule1 ? 'bg-emerald-500/20 border-emerald-500/50 text-emerald-200 font-bold' : 'bg-slate-800/60 border-slate-700 text-slate-300'
                }`}>
                  <span>1. Actual HRA Received</span>
                  <span className="font-mono">₹{Math.round(rule1).toLocaleString('en-IN')}</span>
                </div>
                <div className={`p-2.5 rounded-xl border text-xs flex justify-between items-center ${
                  exemptHraAnnual === rule2 ? 'bg-emerald-500/20 border-emerald-500/50 text-emerald-200 font-bold' : 'bg-slate-800/60 border-slate-700 text-slate-300'
                }`}>
                  <span>2. {isMetro ? '50%' : '40%'} of Salary</span>
                  <span className="font-mono">₹{Math.round(rule2).toLocaleString('en-IN')}</span>
                </div>
                <div className={`p-2.5 rounded-xl border text-xs flex justify-between items-center ${
                  exemptHraAnnual === rule3 ? 'bg-emerald-500/20 border-emerald-500/50 text-emerald-200 font-bold' : 'bg-slate-800/60 border-slate-700 text-slate-300'
                }`}>
                  <span>3. Rent Paid - 10% Salary</span>
                  <span className="font-mono">₹{Math.round(rule3).toLocaleString('en-IN')}</span>
                </div>
              </div>

              {/* Download Statement Button */}
              <div className="mt-5 pt-4 border-t border-slate-800">
                <button
                  type="button"
                  onClick={downloadHraStatement}
                  className="w-full py-2.5 px-4 bg-emerald-500 hover:bg-emerald-400 active:bg-emerald-600 text-slate-950 font-bold text-xs rounded-xl shadow-md transition-all flex items-center justify-center gap-2 cursor-pointer"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download HRA Exemption Statement (.txt)</span>
                </button>
              </div>
            </div>

            {/* CTA Box */}
            <div className="bg-white rounded-3xl p-6 border border-slate-200 shadow-sm space-y-3">
              <div className="flex items-center gap-2 text-slate-900 font-bold text-sm">
                <ShieldCheck className="w-5 h-5 text-emerald-600" />
                <span>Claim HRA Exemption in your ITR</span>
              </div>
              <p className="text-xs text-slate-500">
                Submit rent receipts and landlord PAN directly to our Chartered Accountants for 100% verified notice-free filing.
              </p>
              <Link
                href="/services/itr-filing"
                className="w-full py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white text-center font-bold text-xs rounded-xl shadow-md flex items-center justify-center gap-1.5 transition-all"
              >
                <span>File ITR with HRA Exemption</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
